import type { Dict } from './types';

export const UI: Record<'en' | 'fr', Dict> = {
  "en": {
    "nav.work": "Work",
    "nav.awards": "Awards",
    "nav.journey": "Journey",
    "nav.stack": "Stack",
    "nav.writing": "Writing",
    "nav.contact": "Contact",
    "cta.talk": "Get in touch",
    "cta.work": "See my work",
    "menu": "Menu",
    "theme": "Switch theme",
    "close": "Close",
    "hero.status": "Software Engineer at <b>Sawego Digital</b>",
    "hero.hi": "Hey, I’m Steve Gwade.",
    "hero.sub": "Software engineer based in <b>Yaounde, Cameroon</b>. Over two years shipping to production.",
    "hero.hint": "Hover the photo",
    "f.loc": "Based in",
    "f.locv": "Yaounde, Cameroon",
    "f.time": "local time",
    "f.exp": "Experience",
    "f.expv": "2.5 years",
    "f.expd": "Shipping to production",
    "f.edu": "Education",
    "f.eduv": "MSc, Distinction",
    "f.edud": "Data Science and AI, 2025",
    "f.now": "Currently",
    "f.nowd": "Software Engineer",
    "f.win": "Recent win",
    "f.winv": "1st of 179 teams",
    "f.wind": "Huawei ICT 2025, worldwide",
    "f.stack": "Daily stack",
    "work.k": "Selected work",
    "work.h": "Things I’ve <em>built</em>",
    "work.p": "Company platforms, research and competition wins. Open one for the story and the links.",
    "more.h": "More projects",
    "more.n": "{n} more",
    "aw.k": "Recognition",
    "aw.h": "Awards and <em>wins</em>",
    "aw.p": "Four awards in 2025. Point at a bubble to read the story.",
    "aw.pt": "Four awards in 2025. Tap a bubble to read the story.",
    "aw.see": "See {p}",
    "jy.k": "Journey",
    "jy.h": "Where I’ve <em>worked</em>",
    "jy.p": "Six chapters since 2020. Open a role for the full picture.",
    "jy.view": "View role",
    "jy.year": "Year",
    "wr.k": "Writing",
    "wr.h": "Notes and <em>essays</em>",
    "wr.p": "Longer reads on maths, machine learning and the ideas behind my open source work.",
    "wr.tldr": "In short",
    "wr.take": "Key takeaways",
    "wr.refs": "Further reading",
    "wr.contents": "Contents",
    "wr.more": "More essays",
    "wr.secs": "{n} sections",
    "wr.min": "min read",
    "wr.read": "Read",
    "wr.back": "Back",
    "wr.link": "Copy link",
    "wr.linked": "Link copied",
    "wr.prev": "Previous",
    "wr.nextp": "Next",
    "wr.sample": "Sample",
    "wr.by": "Steve Gwade",
    "st.k": "Stack",
    "st.h": "What I <em>build with</em>",
    "st.hint": "Spin the globe, then pick an area or a project to see its tools connect.",
    "st.groups": "By area",
    "st.projects": "By project",
    "st.drag": "Drag to spin",
    "st.open": "Open project",
    "st.used": "Used in",
    "st.idle": "<b>22 tools, one globe</b>Pick an area or a project above, or point at any tool.",
    "ct.k": "Contact",
    "ct.h": "Let’s<br>talk<em>.</em>",
    "ct.p": "Pick a topic and I’ll draft the note. Copy it, or send it straight from your inbox.",
    "ct.now": "Building at Sawego Digital",
    "ct.to": "To",
    "ct.about": "Topic",
    "ct.area": "Area",
    "ct.copy": "copy the text",
    "ct.copied": "Copied",
    "ct.send": "Send this email",
    "ct.gmail": "open in Gmail",
    "ct.or": "or",
    "ct.cv": "Resume",
    "ct.cvd": "PDF, 2 pages",
    "mail.copied": "Email copied",
    "mail.done": "Copied to clipboard",
    "ft.top": "Back to top",
    "dt.role": "Role",
    "dt.where": "Where",
    "dt.built": "Built with",
    "dt.impact": "Impact",
    "dt.pb": "The problem",
    "dt.sum": "What changed",
    "dt.prev": "Previous",
    "dt.next": "Next",
    "dt.shot": "Screenshot",
    "dt.rel": "Projects from this role",
    "present": "Present"
  },
  "fr": {
    "nav.work": "Projets",
    "nav.awards": "Prix",
    "nav.journey": "Parcours",
    "nav.stack": "Outils",
    "nav.writing": "Écrits",
    "nav.contact": "Contact",
    "cta.talk": "Me contacter",
    "cta.work": "Voir mes projets",
    "menu": "Menu",
    "theme": "Changer de thème",
    "close": "Fermer",
    "hero.status": "Ingénieur logiciel chez <b>Sawego Digital</b>",
    "hero.hi": "Salut, moi c’est Steve Gwade.",
    "hero.sub": "Ingénieur logiciel basé à <b>Yaoundé, Cameroun</b>. Plus de deux ans de mises en production.",
    "hero.hint": "Survolez la photo",
    "f.loc": "Basé à",
    "f.locv": "Yaoundé, Cameroun",
    "f.time": "heure locale",
    "f.exp": "Expérience",
    "f.expv": "2,5 ans",
    "f.expd": "Mises en production",
    "f.edu": "Formation",
    "f.eduv": "Master, mention",
    "f.edud": "Data Science et IA, 2025",
    "f.now": "Actuellement",
    "f.nowd": "Ingénieur logiciel",
    "f.win": "Dernier titre",
    "f.winv": "1er sur 179 équipes",
    "f.wind": "Huawei ICT 2025, mondial",
    "f.stack": "Stack au quotidien",
    "work.k": "Projets choisis",
    "work.h": "Ce que j’ai <em>construit</em>",
    "work.p": "Plateformes d’entreprise, recherche et compétitions. Ouvrez-en un pour l’histoire et les liens.",
    "more.h": "Autres projets",
    "more.n": "{n} de plus",
    "aw.k": "Reconnaissance",
    "aw.h": "Prix et <em>distinctions</em>",
    "aw.p": "Quatre prix en 2025. Survolez une bulle pour lire l’histoire.",
    "aw.pt": "Quatre prix en 2025. Touchez une bulle pour lire l’histoire.",
    "aw.see": "Voir {p}",
    "jy.k": "Parcours",
    "jy.h": "Où j’ai <em>travaillé</em>",
    "jy.p": "Six étapes depuis 2020. Ouvrez un poste pour tout voir.",
    "jy.view": "Voir le poste",
    "jy.year": "Année",
    "wr.k": "Écrits",
    "wr.h": "Notes et <em>essais</em>",
    "wr.p": "Des lectures plus longues sur les maths, le machine learning et les idées derrière mes projets open source.",
    "wr.tldr": "En bref",
    "wr.take": "À retenir",
    "wr.refs": "Pour aller plus loin",
    "wr.contents": "Sommaire",
    "wr.more": "Autres essais",
    "wr.secs": "{n} sections",
    "wr.min": "min de lecture",
    "wr.read": "Lire",
    "wr.back": "Retour",
    "wr.link": "Copier le lien",
    "wr.linked": "Lien copié",
    "wr.prev": "Précédent",
    "wr.nextp": "Suivant",
    "wr.sample": "Exemple",
    "wr.by": "Steve Gwade",
    "st.k": "Outils",
    "st.h": "Avec quoi je <em>construis</em>",
    "st.hint": "Faites tourner le globe, puis choisissez un domaine ou un projet pour relier ses outils.",
    "st.groups": "Par domaine",
    "st.projects": "Par projet",
    "st.drag": "Glissez pour tourner",
    "st.open": "Voir le projet",
    "st.used": "Utilisé dans",
    "st.idle": "<b>22 outils, un globe</b>Choisissez un domaine ou un projet ci-dessus, ou survolez un outil.",
    "ct.k": "Contact",
    "ct.h": "Parlons-<br>en<em>.</em>",
    "ct.p": "Choisissez un sujet, je rédige le message. Copiez-le, ou envoyez-le depuis votre messagerie.",
    "ct.now": "En poste chez Sawego Digital",
    "ct.to": "À",
    "ct.about": "Sujet",
    "ct.area": "Domaine",
    "ct.copy": "copier le texte",
    "ct.copied": "Copié",
    "ct.send": "Envoyer cet e-mail",
    "ct.gmail": "ouvrir dans Gmail",
    "ct.or": "ou",
    "ct.cv": "CV",
    "ct.cvd": "PDF, 2 pages",
    "mail.copied": "E-mail copié",
    "mail.done": "Copié dans le presse-papiers",
    "ft.top": "Haut de page",
    "dt.role": "Rôle",
    "dt.where": "Où",
    "dt.built": "Technologies",
    "dt.impact": "Impact",
    "dt.pb": "Le problème",
    "dt.sum": "Ce qui a changé",
    "dt.prev": "Précédent",
    "dt.next": "Suivant",
    "dt.shot": "Capture d’écran",
    "dt.rel": "Projets de ce poste",
    "present": "Aujourd’hui"
  }
};

export const ROLE_LINES: Record<'en' | 'fr', string[]> = {
  "en": [
    "I design systems.",
    "I ship AI.",
    "I scale backends.",
    "I build to last."
  ],
  "fr": [
    "Je conçois des systèmes.",
    "J’industrialise l’IA.",
    "Je fais tenir la charge.",
    "Je bâtis pour durer."
  ]
};

export const MONTHS: Record<'en' | 'fr', string[]> = {
  "en": [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec"
  ],
  "fr": [
    "janv.",
    "févr.",
    "mars",
    "avr.",
    "mai",
    "juin",
    "juil.",
    "août",
    "sept.",
    "oct.",
    "nov.",
    "déc."
  ]
};
